spring.application.name=club
spring.datasource.url=jdbc:postgresql://localhost:5432/qrclub
spring.datasource.username=qrclub_user
spring.datasource.password=qrclub_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect