version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: qr-club-postgres
    restart: always
    environment:
      POSTGRES_DB: qrclub
      POSTGRES_USER: qrclub_user
      POSTGRES_PASSWORD: qrclub_pass
    ports:
      - "5432:5432"
    volumes:
      - qrclub_pgdata:/var/lib/postgresql/data

volumes:
  qrclub_pgdata: